// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnZXbIaocPvYes192iVMwdnrUpBhEZPZg',
    appId: '1:402130650347:web:001658fc2df58f291f6aae',
    messagingSenderId: '402130650347',
    projectId: 'fcm-4b8c8',
    authDomain: 'fcm-4b8c8.firebaseapp.com',
    storageBucket: 'fcm-4b8c8.firebasestorage.app',
    measurementId: 'G-X1W93TT8KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA32gcoYPtuR_DSWW2xeKvjVz96d23bN68',
    appId: '1:402130650347:android:a9a3f40e80d1a8ff1f6aae',
    messagingSenderId: '402130650347',
    projectId: 'fcm-4b8c8',
    storageBucket: 'fcm-4b8c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG5utTGWAGTmdcacWox_liNVdexer9U9M',
    appId: '1:402130650347:ios:64f1137e591276be1f6aae',
    messagingSenderId: '402130650347',
    projectId: 'fcm-4b8c8',
    storageBucket: 'fcm-4b8c8.firebasestorage.app',
    iosBundleId: 'com.example.fcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG5utTGWAGTmdcacWox_liNVdexer9U9M',
    appId: '1:402130650347:ios:64f1137e591276be1f6aae',
    messagingSenderId: '402130650347',
    projectId: 'fcm-4b8c8',
    storageBucket: 'fcm-4b8c8.firebasestorage.app',
    iosBundleId: 'com.example.fcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnZXbIaocPvYes192iVMwdnrUpBhEZPZg',
    appId: '1:402130650347:web:952efb3dbf2fe2091f6aae',
    messagingSenderId: '402130650347',
    projectId: 'fcm-4b8c8',
    authDomain: 'fcm-4b8c8.firebaseapp.com',
    storageBucket: 'fcm-4b8c8.firebasestorage.app',
    measurementId: 'G-SQ9ZRHFVJX',
  );

}